### PR TITLE
air pollution visualization

### PR DESCRIPTION
**Pull request by AbstractMonkey**
# Description

A visualization that depicts how air pollution decreased during the COVID-19 quarantine in Los Angeles. Utilizes air pollution data from the EPA in the form of a CSV, and COVID-19 infection data also from a CSV.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Change Status

- [x] Complete, but not tested (may need new tests)

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by CVanchieri — COMMENTED** [review]
Nice visualization, all looks good.

AirPoulltionCovid19

**Review by serinamarie — APPROVED** [review]
What a lovely visualized insight. I approve!

**Review by serinamarie — APPROVED** [review]
Looks good :)

**Review by CVanchieri — APPROVED** [review]
Nice correlation graph.

**Pull request merged**
